package com.mm.tnxrs.common.model;

import com.mm.tnxrs.common.model.base.BaseCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	
}
