package com.mm.tnxrs.common.model;

import com.mm.tnxrs.common.model.base.BaseSerial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Serial extends BaseSerial<Serial> {
	
}
